parameters:
    cart.storage.session_key: cart

services:
    cart.storage.session:
        class: lesson04\example04\cart\storage\SessionStorage
        arguments: ['%cart.storage.session_key%']
        # shared: false

    cart.calculator:
        class: lesson04\example04\cart\cost\SimpleCost

    cart:
        class: lesson04\example04\cart\Cart
        arguments: ['@cart.storage.session', '@cart.calculator']
        # autowire: true